# Generated by Django 3.2 on 2021-04-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
